[package]
name = "calculate"
version = "0.1.0"
authors = ["还不如一只猪威武 <liamxin@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.3.1-alpha1"

[features]
default = []
light-theme = []